//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevRainSolutions.KyivSmartCity.New.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevRainSolutions.KyivSmartCity.New.App_GlobalResources.ValidationResources", typeof(ValidationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value with a valid mimetype..
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Індекс, адреса.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Група крові.
        /// </summary>
        public static string BloodGroupId {
            get {
                return ResourceManager.GetString("BloodGroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Місто.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Місто.
        /// </summary>
        public static string CityId {
            get {
                return ResourceManager.GetString("CityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підтвердити новий пароль.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контактна людина.
        /// </summary>
        public static string ContactPerson {
            get {
                return ResourceManager.GetString("ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid credit card number..
        /// </summary>
        public static string Creditcard {
            get {
                return ResourceManager.GetString("Creditcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть вірну дату..
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid date (ISO)..
        /// </summary>
        public static string DateISO {
            get {
                return ResourceManager.GetString("DateISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата здачі.
        /// </summary>
        public static string DateOccured {
            get {
                return ResourceManager.GetString("DateOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата народження.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата смерті.
        /// </summary>
        public static string DateOfDead {
            get {
                return ResourceManager.GetString("DateOfDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата реєстрації.
        /// </summary>
        public static string DateRegistered {
            get {
                return ResourceManager.GetString("DateRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть вірну дату та час..
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле може містити лише числа..
        /// </summary>
        public static string Digits {
            get {
                return ResourceManager.GetString("Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва хвороби.
        /// </summary>
        public static string Disease {
            get {
                return ResourceManager.GetString("Disease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип здачі.
        /// </summary>
        public static string DonationType {
            get {
                return ResourceManager.GetString("DonationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Центр здачі крові.
        /// </summary>
        public static string DonorCenter {
            get {
                return ResourceManager.GetString("DonorCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шаблон для &quot;{0}&quot; не знайдено..
        /// </summary>
        public static string EditorTemplateNotFoundFor {
            get {
                return ResourceManager.GetString("EditorTemplateNotFoundFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електронна адреса.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть коректну електронну адресу..
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть це саме значення ще раз..
        /// </summary>
        public static string EqualTo {
            get {
                return ResourceManager.GetString("EqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть коректну дату для &quot;{0}&quot;..
        /// </summary>
        public static string FieldMustBeDate {
            get {
                return ResourceManager.GetString("FieldMustBeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть коректне число для&quot;{0}&quot;..
        /// </summary>
        public static string FieldMustBeNumeric {
            get {
                return ResourceManager.GetString("FieldMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви невірно ввели перевірочне слово. Будь ласка, спробуйте ще раз..
        /// </summary>
        public static string IncorrectVerificationWord {
            get {
                return ResourceManager.GetString("IncorrectVerificationWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка авторизації. Перевірте правильність логіну та паролю..
        /// </summary>
        public static string InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid property value: {0}.
        /// </summary>
        public static string InvalidPropertyValue {
            get {
                return ResourceManager.GetString("InvalidPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прізвище.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логін.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть значення, що не більше або дорівнює {0}..
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значення поля \&quot;{0}\&quot; має бути не більше, ніж {0} символів..
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По батькові.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value greater than or equal to {0}..
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будь ласка, введіть для &quot;{0}&quot;, як мінімум, {2} символів..
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новий пароль.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коментарі.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть коректне число..
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поточний пароль.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введений та перевірочний паролі не співпадають..
        /// </summary>
        public static string PasswordAndConfirmationDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordAndConfirmationDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посилання на фото.
        /// </summary>
        public static string PhotoImage {
            get {
                return ResourceManager.GetString("PhotoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &quot;{0}&quot; is invalid for the property &quot;{1}&quot;.
        /// </summary>
        public static string PropertyValueInvalid {
            get {
                return ResourceManager.GetString("PropertyValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;{0}&quot; обов&apos;язкове для заповнення..
        /// </summary>
        public static string PropertyValueRequired {
            get {
                return ResourceManager.GetString("PropertyValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value between {1} and {2}..
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value between {0} and {1}..
        /// </summary>
        public static string RangeClient {
            get {
                return ResourceManager.GetString("RangeClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value between {0} and {1} characters long..
        /// </summary>
        public static string RangeLength {
            get {
                return ResourceManager.GetString("RangeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реципієнт.
        /// </summary>
        public static string Recipient {
            get {
                return ResourceManager.GetString("Recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Область прописки.
        /// </summary>
        public static string RegionId {
            get {
                return ResourceManager.GetString("RegionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запам&apos;ятати?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевірте правильність введенного значення..
        /// </summary>
        public static string Remote {
            get {
                return ResourceManager.GetString("Remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виберіть, як мінімум, один тип кроводачі..
        /// </summary>
        public static string SelectBloodType {
            get {
                return ResourceManager.GetString("SelectBloodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стать.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an integer value, sign allowed..
        /// </summary>
        public static string SignedInt {
            get {
                return ResourceManager.GetString("SignedInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип сповіщень.
        /// </summary>
        public static string SubscriptionTypeId {
            get {
                return ResourceManager.GetString("SubscriptionTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть коректне значення часу..
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть ціле число, що більше 0..
        /// </summary>
        public static string UnsignedInt {
            get {
                return ResourceManager.GetString("UnsignedInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть посилання у коректному форматі..
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електронна адреса.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;null&gt;.
        /// </summary>
        public static string ValueNull {
            get {
                return ResourceManager.GetString("ValueNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Волонтер з такою адресою вже існує..
        /// </summary>
        public static string VolunteerExists {
            get {
                return ResourceManager.GetString("VolunteerExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип роботи.
        /// </summary>
        public static string VolunteerWorkType {
            get {
                return ResourceManager.GetString("VolunteerWorkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ця електронная адреса не підтверджена..
        /// </summary>
        public static string YouMustHaveConfirmedEmailToLogOn {
            get {
                return ResourceManager.GetString("YouMustHaveConfirmedEmailToLogOn", resourceCulture);
            }
        }
    }
}
